apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomoto-deployment
spec:
  selector:
    matchLabels:
      app: zomoto
  replicas: 2
  template:
    metadata:
      labels:
        app: zomoto
    spec:
      containers:
        - name: zomoto
          image: ayanshishika/zomoto:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: zomoto-ssvc
spec:
  selector:
    app: zomoto
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: LoadBalancer

